import { ClientProps } from '@/domain/entities/Client';

const now = new Date();
const twoDaysAgo = new Date(now); twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
const oneWeekAgo = new Date(now); oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
const fifteenDaysAgo = new Date(now); fifteenDaysAgo.setDate(fifteenDaysAgo.getDate() - 15);
const twoMonthsAgo = new Date(now); twoMonthsAgo.setMonth(now.getMonth() - 2);
const sixMonthsAgo = new Date(now); sixMonthsAgo.setMonth(now.getMonth() - 6);
const oneYearAgo = new Date(now); oneYearAgo.setFullYear(now.getFullYear() - 1);
const twoYearsAgo = new Date(now); twoYearsAgo.setFullYear(now.getFullYear() - 2);

export const seedClients: ClientProps[] = [
    {
        id: 'usr_admin_01',
        email: 'admin@voidsystem.com',
        fullName: 'Admin User',
        role: 'admin',
        xp: 0,
        level: 'iniciado',
        totalSpent: 0,
        totalSessions: 0,
        preferences: {},
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 'usr_cli_01',
        fullName: 'Ana Silva',
        email: 'ana.silva@example.com',
        role: 'client',
        phone: '5541999100001',
        cpf: '123.456.789-00',
        birthDate: '1992-03-15',
        addressNeighborhood: 'Água Verde',
        addressCity: 'Curitiba',
        profession: 'Engenheira',
        leadSource: 'Instagram',
        npsScore: 10,
        lastSurveyDate: twoDaysAgo,
        membershipTier: 'void_club',
        xp: 3200,
        level: 'mestre',
        totalSpent: 4580,
        totalSessions: 32,
        firstVisit: twoYearsAgo,
        lastVisit: twoDaysAgo,
        preferences: { temperature: 35.5, lighting: false, claustrophobiaNotes: '', physicalPainNotes: 'Dor lombar leve' },
        createdAt: twoYearsAgo,
        updatedAt: twoDaysAgo,
        // Rich Data
        usageTags: ['focada', 'busca relaxamento', 'alto ticket'],
        preferredWeekDays: ['Sexta-feira', 'Sábado'],
        visitHistory: [twoDaysAgo, fifteenDaysAgo, twoMonthsAgo, sixMonthsAgo, oneYearAgo],
        purchaseHistory: [
            { id: 'p1', date: twoDaysAgo, itemName: 'Pacote 3 Floats', value: 450 },
            { id: 'p2', date: twoMonthsAgo, itemName: 'Produto: Vela Aromática', value: 80 },
            { id: 'p3', date: sixMonthsAgo, itemName: 'Membership Void Club', value: 1200 }
        ],
        interactionHistory: [
            { id: 'i1', date: twoDaysAgo, type: 'visit', notes: 'Sessão tranquila, elogiou a limpeza.' },
            { id: 'i2', date: oneWeekAgo, type: 'message', notes: 'Perguntou sobre disponibilidade no feriado.' },
            { id: 'i3', date: twoMonthsAgo, type: 'call', notes: 'Ligação de Feedback NPS (Nota 10).' }
        ]
    },
    {
        id: 'usr_cli_02',
        fullName: 'Carlos Mendes',
        email: 'carlos.mendes@example.com',
        role: 'client',
        phone: '5541998200002',
        cpf: '234.567.890-11',
        birthDate: '1985-07-22',
        addressNeighborhood: 'Batel',
        addressCity: 'Curitiba',
        profession: 'Médico',
        leadSource: 'Indicação',
        membershipTier: 'standard',
        xp: 150,
        level: 'iniciado',
        totalSpent: 450,
        totalSessions: 2,
        firstVisit: twoMonthsAgo,
        lastVisit: fifteenDaysAgo,
        preferences: { temperature: 36.0, lighting: true },
        createdAt: twoMonthsAgo,
        updatedAt: fifteenDaysAgo,
    },
    {
        id: 'usr_cli_03',
        fullName: 'Fernanda Costa',
        email: 'fernanda.costa@example.com',
        role: 'client',
        phone: '5541997300003',
        cpf: '345.678.901-22',
        birthDate: '1990-11-08',
        addressNeighborhood: 'Centro Cívico',
        addressCity: 'Curitiba',
        profession: 'Advogada',
        leadSource: 'Indicação',
        npsScore: 9,
        lastSurveyDate: oneWeekAgo,
        membershipTier: 'vip',
        xp: 12500,
        level: 'voidwalker',
        totalSpent: 18900,
        totalSessions: 120,
        firstVisit: twoYearsAgo,
        lastVisit: twoDaysAgo,
        preferences: { temperature: 35.0, lighting: false, claustrophobiaNotes: '', physicalPainNotes: '' },
        createdAt: twoYearsAgo,
        updatedAt: twoDaysAgo,
    },
    {
        id: 'usr_cli_04',
        fullName: 'Lucas Oliveira',
        email: 'lucas.oliveira@example.com',
        role: 'client',
        phone: '5541996400004',
        cpf: '456.789.012-33',
        birthDate: '1998-01-30',
        addressNeighborhood: 'Juvevê',
        addressCity: 'Curitiba',
        profession: 'Designer',
        leadSource: 'Instagram',
        membershipTier: 'standard',
        xp: 450,
        level: 'explorador',
        totalSpent: 1200,
        totalSessions: 5,
        firstVisit: sixMonthsAgo,
        lastVisit: oneWeekAgo,
        preferences: { temperature: 35.8, lighting: true, claustrophobiaNotes: 'Prefere tampa semi-aberta' },
        createdAt: sixMonthsAgo,
        updatedAt: oneWeekAgo,
    },
    {
        id: 'usr_cli_05',
        fullName: 'Mariana Rocha',
        email: 'mariana.rocha@example.com',
        role: 'client',
        phone: '5541995500005',
        cpf: '567.890.123-44',
        birthDate: '1988-05-12',
        addressNeighborhood: 'Mercês',
        addressCity: 'Curitiba',
        profession: 'Psicóloga',
        leadSource: 'Indicação',
        membershipTier: 'void_club',
        xp: 1800,
        level: 'habitue',
        totalSpent: 6200,
        totalSessions: 18,
        firstVisit: oneYearAgo,
        lastVisit: oneWeekAgo,
        preferences: { temperature: 35.2, lighting: false, physicalPainNotes: 'Fibromialgia — sessões reduzidas' },
        createdAt: oneYearAgo,
        updatedAt: oneWeekAgo,
    },
    {
        id: 'usr_cli_06',
        fullName: 'Pedro Santos',
        email: 'pedro.santos@example.com',
        role: 'client',
        phone: '5541994600006',
        cpf: '678.901.234-55',
        birthDate: '1995-09-18',
        addressNeighborhood: 'Bigorrilho',
        addressCity: 'Curitiba',
        profession: 'Dentista',
        leadSource: 'Instagram',
        membershipTier: 'standard',
        xp: 80,
        level: 'iniciado',
        totalSpent: 150,
        totalSessions: 1,
        firstVisit: fifteenDaysAgo,
        lastVisit: fifteenDaysAgo,
        preferences: { temperature: 36.0, lighting: true },
        createdAt: fifteenDaysAgo,
        updatedAt: fifteenDaysAgo,
    },
    {
        id: 'usr_cli_07',
        fullName: 'Juliana Alves',
        email: 'juliana.alves@example.com',
        role: 'client',
        phone: '5541993700007',
        addressCity: 'Pinhais',
        profession: 'Biomédica',
        leadSource: 'outro',
        membershipTier: 'standard',
        xp: 600,
        level: 'explorador',
        totalSpent: 1950,
        totalSessions: 7,
        firstVisit: sixMonthsAgo,
        lastVisit: twoDaysAgo,
        preferences: { temperature: 35.5, lighting: false },
        createdAt: sixMonthsAgo,
        updatedAt: twoDaysAgo,
    },
    {
        id: 'usr_cli_08',
        fullName: 'Rafael Lima',
        email: 'rafael.lima@example.com',
        role: 'client',
        phone: '5541992800008',
        addressNeighborhood: 'Bacacheri',
        addressCity: 'Curitiba',
        profession: 'Marketing',
        leadSource: 'Instagram',
        membershipTier: 'standard',
        xp: 350,
        level: 'explorador',
        totalSpent: 900,
        totalSessions: 4,
        firstVisit: twoMonthsAgo,
        lastVisit: twoMonthsAgo,
        preferences: { temperature: 35.5, lighting: true },
        createdAt: twoMonthsAgo,
        updatedAt: twoMonthsAgo,
    },
];
